### ISSUE TITLE
can't get libdl.so

### ISSUE THREAD

**Issue by cybbro** [benjamimgois-zz/goverlay#206]
I have just installed Goverlay via ppa, on fresh Ubuntu 22.04, and it wouldn't start, I get that error
`
can't get libdl.so
`

![image](https://user-images.githubusercontent.com/10908092/164546068-1b73e874-29bf-4af2-bd47-cf6a1008c4dc.png)

**Comment by EnderIce2** [comment]
I have the same issue. I fixed by installing the [goverlay_0.6.1-1~focal1.0_amd64.deb](http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu/pool/main/g/goverlay/goverlay_0.6.1-1~focal1.0_amd64.deb) from launchpad

**Comment by massatt212** [comment]
i really hope they fix that soon

**Comment by cybbro** [comment]
> I had the same issue. I fixed by installing the [goverlay_0.6.1-1~focal1.0_amd64.deb](http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu/pool/main/g/goverlay/goverlay_0.6.1-1~focal1.0_amd64.deb) from launchpad

Thank you, this did work!

**Comment by massatt212** [comment]
Will this give me the missing file to run goverlay ver 8

**Comment by TheMarfy** [comment]
Hello there! :-)
there are some issue that newer GOverlay versions depend on newer libraries than Ubuntu 22.04 repos provides.
See: https://github.com/benjamimgois-zz/goverlay/issues/197#issuecomment-1079005410

You can work around that GOverlay doesn't start by using the prebuild binary from the GitHub releases here [0.8.1](https://github.com/benjamimgois-zz/goverlay/releases/tag/0.8.1).  But you have to install first a newer version of libQt5Pass. See: https://github.com/benjamimgois-zz/goverlay/issues/197#issuecomment-1107455270

To start the prebuild GOverlay you want to use this command:
`./goverlay --style breeze`

Attention please: mangohud still has issues out of the box for OpenGL apps under Ubuntu 22.04! 
This is maybe the cause of the error in the first place, because newer GOverlay versions want to draw a 3D cube as preview for the MangoHUD position. If you run GOverlay as intended by using:
```
marf@blackdrake:~/Downloads/goverlay_0_8_1$ QT_QPA_PLATFORM=xcb mangohud --dlsym ./goverlay --style breeze
can't get libdl.so
```
... the error is reported.

Same with glxgears:
```
marf@blackdrake:~/Downloads/goverlay_0_8_1$ mangohud glxgears 
can't get libdl.so
```
So, it seems the error comes originally from MangoHUD instead of GOverlay.

Thanks!

**Comment by cybbro** [comment]
> 

Thank you, this method works for the games I tested!
